com.is1.proyecto.models.Anuncio=com.is1.proyecto.models.Anuncio
com.is1.proyecto.models.AulaAsignacion=com.is1.proyecto.models.AulaAsignacion
com.is1.proyecto.models.Carrera=com.is1.proyecto.models.Carrera
com.is1.proyecto.models.Correlatividad=com.is1.proyecto.models.Correlatividad
com.is1.proyecto.models.DocenteCarrera=com.is1.proyecto.models.DocenteCarrera
com.is1.proyecto.models.DocenteMateria=com.is1.proyecto.models.DocenteMateria
com.is1.proyecto.models.EstadoAcademico=com.is1.proyecto.models.EstadoAcademico
com.is1.proyecto.models.GestorSistema=com.is1.proyecto.models.GestorSistema
com.is1.proyecto.models.InscripcionExamen=com.is1.proyecto.models.InscripcionExamen
com.is1.proyecto.models.Materia=com.is1.proyecto.models.Materia
com.is1.proyecto.models.MateriaPeriodo=com.is1.proyecto.models.MateriaPeriodo
com.is1.proyecto.models.MesaExamen=com.is1.proyecto.models.MesaExamen
com.is1.proyecto.models.Nota=com.is1.proyecto.models.Nota
com.is1.proyecto.models.PlanEstudio=com.is1.proyecto.models.PlanEstudio
com.is1.proyecto.models.SecretariaAcademica=com.is1.proyecto.models.SecretariaAcademica
com.is1.proyecto.models.Sesion=com.is1.proyecto.models.Sesion
com.is1.proyecto.models.Student=com.is1.proyecto.models.Student
com.is1.proyecto.models.Teacher=com.is1.proyecto.models.Teacher
com.is1.proyecto.models.User=com.is1.proyecto.models.User
