com.is1.proyecto.models.AulaAsignacion:default
com.is1.proyecto.models.SecretariaAcademica:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.Sesion:default
com.is1.proyecto.models.Materia:default
com.is1.proyecto.models.MateriaPeriodo:default
com.is1.proyecto.models.Teacher:default
com.is1.proyecto.models.GestorSistema:default
com.is1.proyecto.models.InscripcionExamen:default
com.is1.proyecto.models.Nota:default
com.is1.proyecto.models.DocenteCarrera:default
com.is1.proyecto.models.Correlatividad:default
com.is1.proyecto.models.Anuncio:default
com.is1.proyecto.models.DocenteMateria:default
com.is1.proyecto.models.MesaExamen:default
com.is1.proyecto.models.Student:default
com.is1.proyecto.models.Carrera:default
com.is1.proyecto.models.PlanEstudio:default
com.is1.proyecto.models.EstadoAcademico:default
