com.is1.proyecto.models.Carrera:default
com.is1.proyecto.models.GestorSistema:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.SecretariaAcademica:default
com.is1.proyecto.models.Student:default
com.is1.proyecto.models.PlanEstudio:default
com.is1.proyecto.models.Teacher:default
com.is1.proyecto.models.Sesion:default
